In [1]:
%matplotlib inline
from matplotlib import pyplot as plt
import seaborn as sns

In [4]:
import numpy as np

In [5]:
data = [111,2,4,6]
a = np.array(data)

In [9]:
a.shape

(4,)

In [12]:
a.ndim

1

In [13]:
a.size

4

In [15]:
a.nbytes

32

In [16]:
a.dtype

dtype('int64')

In [18]:
data = [[1,2,3,4],['a','b','c','d']]
b = np.array(data)

In [19]:
b

array([['1', '2', '3', '4'],
       ['a', 'b', 'c', 'd']], 
      dtype='<U21')

In [20]:
b.size

8

In [21]:
b.shape

(2, 4)

In [22]:
b.nbytes

672

In [43]:
e = np.linspace(1, 10, 5)

In [44]:
e

array([  1.  ,   3.25,   5.5 ,   7.75,  10.  ])

In [46]:
a = np.ones((3,3))

In [47]:
a

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [48]:
6*a

array([[ 6.,  6.,  6.],
       [ 6.,  6.,  6.],
       [ 6.,  6.,  6.]])

In [49]:
a

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [2]:
import antipackage
from github.ellisonbg.misc import vizarray as va

Downloading:  https://raw.githubusercontent.com/ellisonbg/misc/master/vizarray.py
Using existing version:  github.ellisonbg.misc.vizarray


In [110]:
a = np.random.randint(0,10,(10,10))

In [ ]:
a = np.random.rand

In [111]:
a

array([[9, 2, 8, 4, 9, 1, 8, 0, 4, 8],
       [6, 9, 7, 7, 5, 1, 9, 4, 0, 7],
       [6, 4, 7, 5, 6, 6, 8, 3, 6, 9],
       [1, 7, 0, 9, 9, 0, 0, 8, 4, 1],
       [2, 3, 3, 3, 1, 0, 5, 0, 4, 9],
       [6, 3, 1, 2, 1, 1, 0, 6, 8, 0],
       [1, 5, 6, 3, 0, 3, 1, 5, 9, 0],
       [4, 3, 7, 9, 7, 0, 1, 5, 9, 6],
       [8, 0, 5, 3, 4, 4, 9, 1, 8, 7],
       [2, 8, 1, 7, 6, 1, 9, 5, 2, 2]])

In [95]:
va.vizarrray(a)

AttributeError: 'module' object has no attribute 'vizarrray'

In [101]:
va.disable()

In [103]:
np.set_printoptions(precision=2)

In [104]:
a

array([[ 0.8 ,  0.98,  0.89,  0.16,  0.66,  0.67,  1.  ,  0.16,  0.99,
         0.57],
       [ 2.59,  2.16,  2.69,  1.1 ,  2.26,  1.67,  2.55,  0.82,  2.64,
         1.32],
       [ 0.95,  0.39,  0.19,  0.44,  0.79,  0.76,  0.48,  0.68,  0.86,
         0.22],
       [ 0.22,  0.99,  0.13,  0.95,  0.72,  0.88,  0.84,  0.88,  0.52,
         0.45],
       [ 0.79,  0.36,  0.51,  0.89,  0.71,  0.31,  0.93,  0.31,  0.6 ,
         0.96],
       [ 0.68,  0.85,  0.54,  0.31,  0.63,  0.81,  0.47,  0.59,  0.08,
         0.69],
       [ 0.86,  0.31,  0.36,  0.73,  0.25,  0.72,  0.33,  0.72,  0.18,
         0.62],
       [ 0.94,  0.62,  0.49,  0.52,  0.91,  0.49,  0.36,  0.09,  0.77,
         0.62],
       [ 0.57,  0.76,  0.66,  0.07,  0.89,  0.98,  0.77,  0.15,  0.9 ,
         0.38],
       [ 0.67,  0.87,  0.58,  0.01,  0.18,  0.11,  0.26,  0.27,  0.63,
         0.47]])

In [98]:
a[0,0]

0.80001370524296767

In [100]:
a[1,:] = a[1,:] + a[0,:]
a

array([[ 0.80001371,  0.98275624,  0.88787432,  0.16333042,  0.66049242,
         0.67315358,  0.99763053,  0.16350211,  0.99448951,  0.56692347],
       [ 2.59472784,  2.15868355,  2.69327649,  1.10169917,  2.25891213,
         1.67097649,  2.55203371,  0.82246251,  2.64336805,  1.31979763],
       [ 0.94550431,  0.39490185,  0.19006545,  0.44345245,  0.79186949,
         0.75706902,  0.47831066,  0.67986419,  0.85829756,  0.21852208],
       [ 0.22034536,  0.99442723,  0.13482489,  0.95163132,  0.7193018 ,
         0.87536356,  0.83756409,  0.88255772,  0.51785484,  0.44526037],
       [ 0.78725748,  0.35803835,  0.5059811 ,  0.88986711,  0.71204795,
         0.30527002,  0.93034801,  0.3091078 ,  0.59675705,  0.9584574 ],
       [ 0.67656376,  0.8488696 ,  0.53659572,  0.30982405,  0.63308506,
         0.81000526,  0.4737756 ,  0.58786662,  0.07767483,  0.68672709],
       [ 0.85685114,  0.30748991,  0.36442762,  0.7319827 ,  0.25492122,
         0.71637175,  0.33031577,  0.72363591,  0.17570073,  0.61848201],
       [ 0.9427425 ,  0.61892937,  0.48555586,  0.52210562,  0.90698553,
         0.48646477,  0.36085379,  0.09499447,  0.773052  ,  0.6153499 ],
       [ 0.57389578,  0.76309048,  0.65753382,  0.07453091,  0.89468832,
         0.98433836,  0.77048586,  0.15237972,  0.90242259,  0.37817773],
       [ 0.67165938,  0.86824039,  0.58468977,  0.00905944,  0.18145763,
         0.10561946,  0.26331185,  0.27222294,  0.63229539,  0.4684873 ]])